export const MessageHelper = {
  PASSWORD_VALID:
    'password must contain uppercase and lowercase letters, numbers and special characters',
  FIRST_NAME_VALID: 'firstName must be only letters',
  LAST_NAME_VALID: 'lastName must be only letters',
  USERNAME_VALID: 'username can not have special characters',
  PASSWORD_OR_EMAIL_INVALID: 'invalid credentials',
  PASSWORD_MIN_VALID: 'password must be at least 8 characters',
  PASSWORD_MAX_VALID: 'password must be a maximum of 30 characters',
  CPF_VALID: 'cpf is invalid',
  TELEPHONE_VALID: 'telephone is invalid',
  STATE_VALID: 'state must be only letters',
  CITY_VALID: 'city must be only letters',
  PAYMENT_VALID: 'payment must be cash, credit_card, debit_card or pix',
  PRODUCT_NAME_VALID: 'product name must be only letters',
  COLOR_VALID: 'color must be only letters',
  SECTION_VALID: 'section must be masculine, feminine or kids',
  PERCENTAGE_VALID: 'percentage must be integer numbers with the symbol %',
  ZIP_CODE_VALID: 'zipCode is invalid',
  EMAIL_INVALID: 'invalid informatiob',
};
